### ISSUE TITLE
Make the "code" optional

### ISSUE THREAD

**Issue by jcrombez** [M6Web/ApiExceptionBundle#4]
Could you make the "code" optional ?
Maybe when code = 0 ?

**Comment by cedvan** [comment]
Hi,

Good idea !
Pull request https://github.com/M6Web/ApiExceptionBundle/pull/6

**Comment by cedvan** [comment]
https://github.com/M6Web/ApiExceptionBundle/pull/6

**Comment by jcrombez** [comment]
great ! thanks :)

**Comment by cedvan** [comment]
**Feature added** in new release [v1.0.1](https://github.com/M6Web/ApiExceptionBundle/releases/tag/v1.0.0)
